# Configuration file for bin processing

# Part 0 General Processing
samples: ['particle', 'supernatant']

# Part 1 Taxonomy Based Processing
TaxonAddThresh: [90, 95, 99]
TaxonRemoveThresh: [90, 95, 99]
TaxonProcessing: ['Original']

# Part 2 ANI Based Processing
ANIAssemblyFilterSize: [5000, 10000]
ANIAssemblySplitSize: 10
ANIAssemblySplits: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
FastANIMinFraction: 0.2
FastANIFragLength: 1000
ANIRepatIdentThreshold: 95
ANIRepatCountThreshold: 20
